INSERT INTO AUTHORITY(ID, NAME) VALUES (1, 'ADMIN');
INSERT INTO AUTHORITY(ID, NAME) VALUES (2, 'USER');
INSERT INTO AUTHORITY(ID, NAME) VALUES (3, 'LOADER');
INSERT INTO AUTHORITY(ID, NAME) VALUES (4, 'MASTER');
INSERT INTO AUTHORITY(ID, NAME) VALUES (5, 'COURIER');
INSERT INTO AUTHORITY(ID, NAME) VALUES (6, 'PURCHASER');