INSERT INTO USER_(ID, USER_NAME, PASSWORD, ACCOUNT_EXPIRED, ACCOUNT_LOCKED, CREDENTIALS_EXPIRED, ENABLED)
  VALUES (1, 'admin', /*adminpassword*/'$2a$04$emkvG7zEO5Dch7UmsWrYc.68It.snXW75gD3hmpgkYm.ZI0vMPbxi', FALSE, FALSE, FALSE, TRUE);

INSERT INTO USER_(ID, USER_NAME, PASSWORD, ACCOUNT_EXPIRED, ACCOUNT_LOCKED, CREDENTIALS_EXPIRED, ENABLED)
  VALUES (2, 'client', /*clientpassword*/'$2a$04$P2/8QCfRAXJN/8MuJTuXjOSKVx2Ms7CcjhSIzdf2RGp1hE9q8RaS.', FALSE, FALSE, FALSE, TRUE);

INSERT INTO USER_(ID, USER_NAME, PASSWORD, ACCOUNT_EXPIRED, ACCOUNT_LOCKED, CREDENTIALS_EXPIRED, ENABLED)
  VALUES (3, 'loader', /*loaderpassword*/'$2a$04$AeANVOoxqdAUmX3k6nFmQuPKjnrqyRpLG36zYsBeTbbKPgXQYECMa', FALSE, FALSE, FALSE, TRUE);

INSERT INTO USER_(ID, USER_NAME, PASSWORD, ACCOUNT_EXPIRED, ACCOUNT_LOCKED, CREDENTIALS_EXPIRED, ENABLED)
  VALUES (4, 'master', /*masterpassword*/'$2a$04$VJMcaNjCc7tcCA1MpiCOMu0W0TCgiuu6TMeAAHEHbMk3x1wQsmfuO', FALSE, FALSE, FALSE, TRUE);

INSERT INTO USER_(ID, USER_NAME, PASSWORD, ACCOUNT_EXPIRED, ACCOUNT_LOCKED, CREDENTIALS_EXPIRED, ENABLED)
  VALUES (5, 'courier', /*courierpassword*/'$2a$04$bWwhaZuIoTsgK4doILGeT.2kWw1z3osEp5AIa6tTjQR/A8oucFrX.', FALSE, FALSE, FALSE, TRUE);

INSERT INTO USER_(ID, USER_NAME, PASSWORD, ACCOUNT_EXPIRED, ACCOUNT_LOCKED, CREDENTIALS_EXPIRED, ENABLED)
  VALUES (6, 'purchaser', /*purchaserpassword*/'$2a$04$jwF8nLOajlFGxl0j0swSW.77pvyxOAsaWs2Tmf0oeA0K8bRbq3JX.', FALSE, FALSE, FALSE, TRUE);

INSERT INTO USERS_AUTHORITIES(USER_ID, AUTHORITY_ID) VALUES (1, 1);
INSERT INTO USERS_AUTHORITIES(USER_ID, AUTHORITY_ID) VALUES (2, 2);
INSERT INTO USERS_AUTHORITIES(USER_ID, AUTHORITY_ID) VALUES (3, 3);
INSERT INTO USERS_AUTHORITIES(USER_ID, AUTHORITY_ID) VALUES (4, 4);
INSERT INTO USERS_AUTHORITIES(USER_ID, AUTHORITY_ID) VALUES (5, 5);
INSERT INTO USERS_AUTHORITIES(USER_ID, AUTHORITY_ID) VALUES (6, 6);