INSERT INTO USER_(ID, USER_NAME, PASSWORD, ACCOUNT_EXPIRED, ACCOUNT_LOCKED, CREDENTIALS_EXPIRED, ENABLED)
  VALUES (1, 'admin', /*adminpassword*/'$2a$04$emkvG7zEO5Dch7UmsWrYc.68It.snXW75gD3hmpgkYm.ZI0vMPbxi', FALSE, FALSE, FALSE, TRUE);

INSERT INTO USER_(ID, USER_NAME, PASSWORD, ACCOUNT_EXPIRED, ACCOUNT_LOCKED, CREDENTIALS_EXPIRED, ENABLED)
  VALUES (21, 'client0', /*client0password*/'$2a$04$n2IVX6nOzm5Fb2LlaCuh3eHWa2pN6rkKtTl.DKGxrRJ2H3MESX7Ru', FALSE, FALSE, FALSE, TRUE);

INSERT INTO USER_(ID, USER_NAME, PASSWORD, ACCOUNT_EXPIRED, ACCOUNT_LOCKED, CREDENTIALS_EXPIRED, ENABLED)
  VALUES (22, 'client1', /*client1password*/'$2a$04$JT/bujcZfyOiiuiIsr//ye8wyva0l6prstxbgbFd0yC7l9XDC5YMm', FALSE, FALSE, FALSE, TRUE);

INSERT INTO USER_(ID, USER_NAME, PASSWORD, ACCOUNT_EXPIRED, ACCOUNT_LOCKED, CREDENTIALS_EXPIRED, ENABLED)
  VALUES (23, 'client2', /*client2password*/'$2a$04$GUnJe07sQkxNhEracQxG6eVGAwHx23ZpRRI5XCVQHYf9Wcc69ND/O', FALSE, FALSE, FALSE, TRUE);

INSERT INTO USER_(ID, USER_NAME, PASSWORD, ACCOUNT_EXPIRED, ACCOUNT_LOCKED, CREDENTIALS_EXPIRED, ENABLED)
  VALUES (3, 'loader', /*loaderpassword*/'$2a$04$AeANVOoxqdAUmX3k6nFmQuPKjnrqyRpLG36zYsBeTbbKPgXQYECMa', FALSE, FALSE, FALSE, TRUE);

INSERT INTO USER_(ID, USER_NAME, PASSWORD, ACCOUNT_EXPIRED, ACCOUNT_LOCKED, CREDENTIALS_EXPIRED, ENABLED)
  VALUES (4, 'master', /*masterpassword*/'$2a$04$VJMcaNjCc7tcCA1MpiCOMu0W0TCgiuu6TMeAAHEHbMk3x1wQsmfuO', FALSE, FALSE, FALSE, TRUE);

INSERT INTO USER_(ID, USER_NAME, PASSWORD, ACCOUNT_EXPIRED, ACCOUNT_LOCKED, CREDENTIALS_EXPIRED, ENABLED)
  VALUES (5, 'courier', /*courierpassword*/'$2a$04$bWwhaZuIoTsgK4doILGeT.2kWw1z3osEp5AIa6tTjQR/A8oucFrX.', FALSE, FALSE, FALSE, TRUE);

INSERT INTO USER_(ID, USER_NAME, PASSWORD, ACCOUNT_EXPIRED, ACCOUNT_LOCKED, CREDENTIALS_EXPIRED, ENABLED)
  VALUES (6, 'purchaser', /*purchaserpassword*/'$2a$04$jwF8nLOajlFGxl0j0swSW.77pvyxOAsaWs2Tmf0oeA0K8bRbq3JX.', FALSE, FALSE, FALSE, TRUE);

INSERT INTO USERS_AUTHORITIES(USER_ID, AUTHORITY_ID) VALUES (1, 1);
INSERT INTO USERS_AUTHORITIES(USER_ID, AUTHORITY_ID) VALUES (21, 2);
INSERT INTO USERS_AUTHORITIES(USER_ID, AUTHORITY_ID) VALUES (22, 2);
INSERT INTO USERS_AUTHORITIES(USER_ID, AUTHORITY_ID) VALUES (23, 2);
INSERT INTO USERS_AUTHORITIES(USER_ID, AUTHORITY_ID) VALUES (3, 3);
INSERT INTO USERS_AUTHORITIES(USER_ID, AUTHORITY_ID) VALUES (4, 4);
INSERT INTO USERS_AUTHORITIES(USER_ID, AUTHORITY_ID) VALUES (5, 5);
INSERT INTO USERS_AUTHORITIES(USER_ID, AUTHORITY_ID) VALUES (6, 6);